version: '3.8'

services:
  db:
    image: postgres:13
    container_name: faux-orator-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d dev_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

volumes:
  postgres_data:
    name: faux-orator-postgres-data

networks:
  dev-network:
    driver: bridge