"""Add AgentSettings model and relationship

Revision ID: 68d9b901a284
Revises: 5bbe3d10791c
Create Date: 2025-01-04 11:56:17.862774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68d9b901a284'
down_revision = '5bbe3d10791c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings_json', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('agent_type')
        batch_op.drop_column('parameters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('agent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('settings_json')

    # ### end Alembic commands ###
