"""Update relationship definitions

Revision ID: e04af9c9dc3e
Revises: 68d9b901a284
Create Date: 2025-01-04 11:58:41.896682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e04af9c9dc3e'
down_revision = '68d9b901a284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('parameters', sa.JSON(), nullable=False))
        batch_op.drop_column('settings_json')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('settings_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('parameters')
        batch_op.drop_column('agent_type')

    # ### end Alembic commands ###
